development:
  adapter: postgresql
  encoding: unicode
  database: blogto_process
  pool: 5
  username: josh
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: blogto_production
  host: localhost
  pool: 5
  username: deploy
  password:
